#!/usr/bin/env python3
"""
Batch 5: Add strings for SparksFeedScreen, SparkStatsScreen,
SparkAddEditorScreen, CreatorsDashboard, ImageEditorScreen
Run from any directory: python3 batch5_strings.py
"""

import os

BASE = "/opt/letheapp/app/src/main/res"

# ── English (default + en) ─────────────────────────────────────────────────
BLOCK_EN = """
    <!-- ── BATCH 5: SPARKS FEED ── -->
    <string name="sparks_feed_no_sparks">No sparks available</string>
    <string name="sparks_feed_back">Back</string>
    <string name="sparks_feed_search">Search</string>
    <string name="sparks_feed_create">Create Spark</string>
    <string name="sparks_feed_my_profile">My Profile</string>
    <string name="sparks_feed_search_placeholder">Search sparks, creators, #tags\u2026</string>
    <string name="sparks_feed_search_close">Close</string>
    <string name="sparks_feed_popular_tags">Popular Tags</string>
    <string name="sparks_feed_section_sparks">Sparks</string>
    <string name="sparks_feed_section_posts">Posts</string>
    <string name="sparks_feed_section_people">People</string>
    <string name="sparks_feed_no_results">No results for \u201c%1$s\u201d</string>
    <string name="sparks_feed_show_fullscreen">Show fullscreen</string>
    <string name="sparks_feed_exit_fullscreen">Exit fullscreen</string>
    <string name="sparks_feed_play">Play</string>
    <string name="sparks_feed_creator">Creator</string>
    <string name="sparks_feed_subscribed">Spark subscription added!</string>
    <string name="sparks_feed_action_like">Like</string>
    <string name="sparks_feed_action_comment">Comment</string>
    <string name="sparks_feed_action_gift">Gift</string>
    <string name="sparks_feed_action_share">Share</string>
    <string name="sparks_feed_comment_placeholder">Comment\u2026</string>
    <string name="sparks_feed_send">Send</string>
    <string name="sparks_feed_comments_count">%1$d Comments</string>
    <string name="sparks_feed_no_comments">No comments yet. Be the first!</string>
    <string name="sparks_feed_reply_to">Reply to @%1$s</string>
    <string name="sparks_feed_spark_link_label">Spark</string>
    <string name="sparks_feed_spark_link_tap">Tap to open</string>
    <string name="sparks_feed_unknown_user">Unknown</string>
    <string name="sparks_feed_gift_title">Gift Styx</string>
    <string name="sparks_feed_gift_support">Support %1$s with Styx coins!</string>
    <string name="sparks_feed_gift_balance">Your balance: %1$d Styx</string>
    <string name="sparks_feed_gift_sent">%1$d Styx gifted!</string>
    <string name="sparks_feed_gift_not_enough">Not enough Styx!</string>
    <string name="sparks_feed_gift_close">Close</string>
    <string name="sparks_feed_share_title">Share Spark</string>
    <string name="sparks_feed_share_external">Share externally</string>
    <string name="sparks_feed_share_external_subtitle">Share link via other apps</string>
    <string name="sparks_feed_share_copy_link">Copy link</string>
    <string name="sparks_feed_share_copy_link_subtitle">External link (web/browser)</string>
    <string name="sparks_feed_share_link_copied">Link copied!</string>
    <string name="sparks_feed_share_send_to">Send to contact</string>
    <string name="sparks_feed_no_contacts">No contacts available</string>
    <string name="sparks_feed_sent_to">Sent to %1$s</string>
    <!-- ── BATCH 5: SPARK STATS ── -->
    <string name="spark_stats_title">Spark Statistics</string>
    <string name="spark_stats_back">Back</string>
    <string name="spark_stats_overview">Overall Overview</string>
    <string name="spark_stats_views">Views</string>
    <string name="spark_stats_likes">Likes</string>
    <string name="spark_stats_subscribers">Subscribers</string>
    <string name="spark_stats_avg_watchtime">Avg. Watchtime: %1$ss</string>
    <string name="spark_stats_per_spark">Per Spark</string>
    <string name="spark_stats_no_sparks">No sparks yet.</string>
    <string name="spark_stats_loops">Loops</string>
    <string name="spark_stats_skips">Skips</string>
    <string name="spark_stats_avg_duration">\u00d8 Watchtime: %1$ss</string>
    <!-- ── BATCH 5: SPARK EDITOR ── -->
    <string name="spark_editor_cancel">Cancel</string>
    <string name="spark_editor_back_to_editor">Back to editor</string>
    <string name="spark_editor_display_duration">Display duration</string>
    <string name="spark_editor_music_start">Music start point</string>
    <string name="spark_editor_title_label">Title</string>
    <string name="spark_editor_title_placeholder">Give your Spark a title\u2026</string>
    <string name="spark_editor_description_label">Description \u00b7 #Tags \u00b7 @Mentions</string>
    <string name="spark_editor_description_placeholder">Describe your Spark\u2026 #Hashtags and @username are possible</string>
    <string name="spark_editor_create_button">Create Spark</string>
    <string name="spark_editor_create_hint">The Spark will be visible in your Creator profile and the Spark feed after creation.</string>
    <string name="spark_editor_clip_suffix">clip</string>
    <string name="spark_editor_uploading">Spark</string>
    <string name="spark_editor_do_not_close">Please do not close</string>
    <string name="spark_editor_music_choose">Choose Music</string>
    <string name="spark_editor_audius_library">Audius Library</string>
    <string name="spark_editor_music_search_placeholder">Search music\u2026 (e.g. \u201celectronic\u201d, \u201chip hop\u201d, \u201cchill\u201d)</string>
    <string name="spark_editor_track_selected">Selected: %1$s</string>
    <string name="spark_editor_ok">OK</string>
    <string name="spark_editor_no_tracks">No tracks found for \u201c%1$s\u201d.</string>
    <string name="spark_editor_add_details">Add details</string>
    <!-- ── BATCH 5: CREATOR DASHBOARD ── -->
    <string name="creator_dash_title">Creator Dashboard</string>
    <string name="creator_dash_more">More</string>
    <string name="creator_dash_spark_stats">Spark Statistics</string>
    <string name="creator_dash_livestream">Livestream</string>
    <string name="creator_dash_new_content">New Content</string>
    <string name="creator_dash_live_badge">LIVE</string>
    <string name="creator_dash_diamonds">Diamonds</string>
    <string name="creator_dash_change_price">Change subscription price</string>
    <string name="creator_dash_set_username">Set username</string>
    <string name="creator_dash_edit_username">Edit username</string>
    <string name="creator_dash_tab_content">Content</string>
    <string name="creator_dash_tab_sparks">Sparks</string>
    <string name="creator_dash_no_content">No content yet.\\nUpload your first post!</string>
    <string name="creator_dash_no_sparks">No sparks yet.\\nUpload your first short video!</string>
    <string name="creator_dash_create_post">Create post</string>
    <string name="creator_dash_create_post_subtitle">Article with text, images and videos</string>
    <string name="creator_dash_create_spark">Create Spark</string>
    <string name="creator_dash_create_spark_subtitle">Short video (always free for subscribers)</string>
    <string name="creator_dash_create_livestream">Livestream</string>
    <string name="creator_dash_create_livestream_subtitle">Go live \u2013 viewers see your stream</string>
    <string name="creator_dash_price_dialog_title">Change subscription price</string>
    <string name="creator_dash_price_free">0 Styx = free for everyone</string>
    <string name="creator_dash_price_label">Price in Styx</string>
    <string name="creator_dash_save">Save</string>
    <string name="creator_dash_cancel">Cancel</string>
    <string name="creator_dash_username_title">Username</string>
    <string name="creator_dash_username_label">@Username (max. 50 characters)</string>
    <string name="creator_dash_delete_spark_title">Delete Spark?</string>
    <string name="creator_dash_delete_post_title">Delete post?</string>
    <string name="creator_dash_delete_confirm">\u201c%1$s\u201d permanently deleted?</string>
    <string name="creator_dash_delete_button">Delete</string>
    <string name="creator_dash_banner_title">Upload banner</string>
    <string name="creator_dash_banner_hint">Recommended: 1500 \u00d7 500 px, JPG or PNG, max. 5 MB.\\nWide landscape, no important content at the edges.</string>
    <string name="creator_dash_avatar_title">Upload profile picture</string>
    <string name="creator_dash_avatar_hint">Recommended: 400 \u00d7 400 px, JPG or PNG, max. 2 MB.\\nSquare image, face clearly visible.</string>
    <string name="creator_dash_choose_image">Choose image</string>
    <string name="creator_dash_banner_cd">Creator Banner</string>
    <string name="creator_dash_edit_banner">Edit banner</string>
    <string name="creator_dash_profile_image_cd">Creator profile picture</string>
    <string name="creator_dash_edit_avatar">Edit profile picture</string>
    <string name="creator_dash_content_preview">Content preview</string>
    <string name="creator_dash_edit">Edit</string>
    <string name="creator_dash_delete">Delete</string>
    <string name="creator_dash_play">Play</string>
    <string name="creator_dash_spark_thumbnail">Spark thumbnail</string>
    <!-- ── BATCH 5: IMAGE EDITOR ── -->
    <string name="image_editor_close">Close</string>
    <string name="image_editor_title">Edit image</string>
    <string name="image_editor_undo">Undo</string>
    <string name="image_editor_add_text">Text</string>
    <string name="image_editor_brush_size">Brush size</string>
    <string name="image_editor_send">Send</string>
    <string name="image_editor_size_label">Size</string>
    <string name="image_editor_text_dialog_title">Add text</string>
    <string name="image_editor_text_input_label">Enter text</string>
    <string name="image_editor_text_color_label">Color:</string>
    <string name="image_editor_add_button">Add</string>
    <string name="image_editor_cancel">Cancel</string>
"""

# ── German ─────────────────────────────────────────────────────────────────
BLOCK_DE = """
    <!-- ── BATCH 5: SPARKS FEED ── -->
    <string name="sparks_feed_no_sparks">Keine Sparks verf\u00fcgbar</string>
    <string name="sparks_feed_back">Zur\u00fcck</string>
    <string name="sparks_feed_search">Suchen</string>
    <string name="sparks_feed_create">Spark erstellen</string>
    <string name="sparks_feed_my_profile">Mein Profil</string>
    <string name="sparks_feed_search_placeholder">Sparks, Creators, #Tags suchen\u2026</string>
    <string name="sparks_feed_search_close">Schlie\u00dfen</string>
    <string name="sparks_feed_popular_tags">Beliebte Tags</string>
    <string name="sparks_feed_section_sparks">Sparks</string>
    <string name="sparks_feed_section_posts">Beitr\u00e4ge</string>
    <string name="sparks_feed_section_people">Personen</string>
    <string name="sparks_feed_no_results">Keine Ergebnisse f\u00fcr \u201e%1$s\u201c</string>
    <string name="sparks_feed_show_fullscreen">In Vollbild anzeigen</string>
    <string name="sparks_feed_exit_fullscreen">Vollbild beenden</string>
    <string name="sparks_feed_play">Play</string>
    <string name="sparks_feed_creator">Creator</string>
    <string name="sparks_feed_subscribed">Spark-Abo hinzugef\u00fcgt!</string>
    <string name="sparks_feed_action_like">Like</string>
    <string name="sparks_feed_action_comment">Kommentar</string>
    <string name="sparks_feed_action_gift">Geschenk</string>
    <string name="sparks_feed_action_share">Teilen</string>
    <string name="sparks_feed_comment_placeholder">Kommentieren\u2026</string>
    <string name="sparks_feed_send">Senden</string>
    <string name="sparks_feed_comments_count">%1$d Kommentare</string>
    <string name="sparks_feed_no_comments">Noch keine Kommentare. Sei der Erste!</string>
    <string name="sparks_feed_reply_to">Antwort an @%1$s</string>
    <string name="sparks_feed_spark_link_label">Spark</string>
    <string name="sparks_feed_spark_link_tap">Tippen zum \u00d6ffnen</string>
    <string name="sparks_feed_unknown_user">Unbekannt</string>
    <string name="sparks_feed_gift_title">Styx verschenken</string>
    <string name="sparks_feed_gift_support">Unterst\u00fctze %1$s mit Styx-Coins!</string>
    <string name="sparks_feed_gift_balance">Dein Guthaben: %1$d Styx</string>
    <string name="sparks_feed_gift_sent">%1$d Styx verschenkt!</string>
    <string name="sparks_feed_gift_not_enough">Nicht genug Styx!</string>
    <string name="sparks_feed_gift_close">Schlie\u00dfen</string>
    <string name="sparks_feed_share_title">Spark teilen</string>
    <string name="sparks_feed_share_external">Extern teilen</string>
    <string name="sparks_feed_share_external_subtitle">Link \u00fcber andere Apps teilen</string>
    <string name="sparks_feed_share_copy_link">Link kopieren</string>
    <string name="sparks_feed_share_copy_link_subtitle">Externer Link (Web/Browser)</string>
    <string name="sparks_feed_share_link_copied">Link kopiert!</string>
    <string name="sparks_feed_share_send_to">An Kontakt senden</string>
    <string name="sparks_feed_no_contacts">Keine Kontakte vorhanden</string>
    <string name="sparks_feed_sent_to">Gesendet an %1$s</string>
    <!-- ── BATCH 5: SPARK STATS ── -->
    <string name="spark_stats_title">Spark-Statistiken</string>
    <string name="spark_stats_back">Zur\u00fcck</string>
    <string name="spark_stats_overview">Gesamt-\u00dcbersicht</string>
    <string name="spark_stats_views">Views</string>
    <string name="spark_stats_likes">Likes</string>
    <string name="spark_stats_subscribers">Abonnenten</string>
    <string name="spark_stats_avg_watchtime">Durchschnittliche Watchtime: %1$ss</string>
    <string name="spark_stats_per_spark">Pro Spark</string>
    <string name="spark_stats_no_sparks">Noch keine Sparks vorhanden.</string>
    <string name="spark_stats_loops">Loops</string>
    <string name="spark_stats_skips">Skips</string>
    <string name="spark_stats_avg_duration">\u00d8 Watchtime: %1$ss</string>
    <!-- ── BATCH 5: SPARK EDITOR ── -->
    <string name="spark_editor_cancel">Abbrechen</string>
    <string name="spark_editor_back_to_editor">Zur\u00fcck zum Editor</string>
    <string name="spark_editor_display_duration">Anzeigedauer</string>
    <string name="spark_editor_music_start">Musik-Startpunkt</string>
    <string name="spark_editor_title_label">Titel</string>
    <string name="spark_editor_title_placeholder">Gib deinem Spark einen Titel\u2026</string>
    <string name="spark_editor_description_label">Beschreibung \u00b7 #Tags \u00b7 @Mentions</string>
    <string name="spark_editor_description_placeholder">Beschreibe deinen Spark\u2026 #Hashtags und @username sind m\u00f6glich</string>
    <string name="spark_editor_create_button">Spark erstellen</string>
    <string name="spark_editor_create_hint">Der Spark wird nach dem Erstellen in deinem Creator-Profil und im Spark-Feed sichtbar.</string>
    <string name="spark_editor_clip_suffix">Ausschnitt</string>
    <string name="spark_editor_uploading">Spark</string>
    <string name="spark_editor_do_not_close">Bitte nicht schlie\u00dfen</string>
    <string name="spark_editor_music_choose">Musik w\u00e4hlen</string>
    <string name="spark_editor_audius_library">Audius Bibliothek</string>
    <string name="spark_editor_music_search_placeholder">Musik suchen\u2026 (z.B. \u201eelectronic\u201c, \u201ehip hop\u201c, \u201echill\u201c)</string>
    <string name="spark_editor_track_selected">Gew\u00e4hlt: %1$s</string>
    <string name="spark_editor_ok">OK</string>
    <string name="spark_editor_no_tracks">Keine Tracks f\u00fcr \u201e%1$s\u201c gefunden.</string>
    <string name="spark_editor_add_details">Details hinzuf\u00fcgen</string>
    <!-- ── BATCH 5: CREATOR DASHBOARD ── -->
    <string name="creator_dash_title">Creator-Dashboard</string>
    <string name="creator_dash_more">Mehr</string>
    <string name="creator_dash_spark_stats">Spark-Statistiken</string>
    <string name="creator_dash_livestream">Livestream</string>
    <string name="creator_dash_new_content">Neuer Inhalt</string>
    <string name="creator_dash_live_badge">LIVE</string>
    <string name="creator_dash_diamonds">Diamanten</string>
    <string name="creator_dash_change_price">Abo-Preis \u00e4ndern</string>
    <string name="creator_dash_set_username">Benutzername setzen</string>
    <string name="creator_dash_edit_username">Benutzername bearbeiten</string>
    <string name="creator_dash_tab_content">Content</string>
    <string name="creator_dash_tab_sparks">Sparks</string>
    <string name="creator_dash_no_content">Noch kein Content vorhanden.\\nLade deinen ersten Beitrag hoch!</string>
    <string name="creator_dash_no_sparks">Noch keine Sparks vorhanden.\\nLade dein erstes Kurzvideo hoch!</string>
    <string name="creator_dash_create_post">Beitrag anlegen</string>
    <string name="creator_dash_create_post_subtitle">Artikel mit Text, Bildern und Videos</string>
    <string name="creator_dash_create_spark">Spark anlegen</string>
    <string name="creator_dash_create_spark_subtitle">Kurzvideo (immer kostenlos f\u00fcr Abonnenten)</string>
    <string name="creator_dash_create_livestream">Livestream</string>
    <string name="creator_dash_create_livestream_subtitle">Gehe live \u2013 Zuschauer sehen deinen Stream</string>
    <string name="creator_dash_price_dialog_title">Abo-Preis \u00e4ndern</string>
    <string name="creator_dash_price_free">0 Styxs = kostenlos f\u00fcr alle</string>
    <string name="creator_dash_price_label">Preis in Styxs</string>
    <string name="creator_dash_save">Speichern</string>
    <string name="creator_dash_cancel">Abbrechen</string>
    <string name="creator_dash_username_title">Benutzername</string>
    <string name="creator_dash_username_label">@Benutzername (max. 50 Zeichen)</string>
    <string name="creator_dash_delete_spark_title">Spark l\u00f6schen?</string>
    <string name="creator_dash_delete_post_title">Beitrag l\u00f6schen?</string>
    <string name="creator_dash_delete_confirm">\u201e%1$s\u201c unwiderruflich l\u00f6schen?</string>
    <string name="creator_dash_delete_button">L\u00f6schen</string>
    <string name="creator_dash_banner_title">Banner hochladen</string>
    <string name="creator_dash_banner_hint">Empfohlen: 1500 \u00d7 500 px, JPG oder PNG, max. 5 MB.\\nBreites Querformat, ohne wichtige Inhalte am Rand.</string>
    <string name="creator_dash_avatar_title">Profilbild hochladen</string>
    <string name="creator_dash_avatar_hint">Empfohlen: 400 \u00d7 400 px, JPG oder PNG, max. 2 MB.\\nQuadratisches Bild, Gesicht gut sichtbar.</string>
    <string name="creator_dash_choose_image">Bild ausw\u00e4hlen</string>
    <string name="creator_dash_banner_cd">Creator Banner</string>
    <string name="creator_dash_edit_banner">Banner bearbeiten</string>
    <string name="creator_dash_profile_image_cd">Creator Profilbild</string>
    <string name="creator_dash_edit_avatar">Profilbild bearbeiten</string>
    <string name="creator_dash_content_preview">Content-Vorschau</string>
    <string name="creator_dash_edit">Bearbeiten</string>
    <string name="creator_dash_delete">L\u00f6schen</string>
    <string name="creator_dash_play">Abspielen</string>
    <string name="creator_dash_spark_thumbnail">Spark-Thumbnail</string>
    <!-- ── BATCH 5: IMAGE EDITOR ── -->
    <string name="image_editor_close">Zur\u00fcck</string>
    <string name="image_editor_title">Bild bearbeiten</string>
    <string name="image_editor_undo">R\u00fckg\u00e4ngig</string>
    <string name="image_editor_add_text">Text</string>
    <string name="image_editor_brush_size">Pinselgr\u00f6\u00dfe</string>
    <string name="image_editor_send">Senden</string>
    <string name="image_editor_size_label">Gr\u00f6\u00dfe</string>
    <string name="image_editor_text_dialog_title">Text hinzuf\u00fcgen</string>
    <string name="image_editor_text_input_label">Text eingeben</string>
    <string name="image_editor_text_color_label">Farbe:</string>
    <string name="image_editor_add_button">Hinzuf\u00fcgen</string>
    <string name="image_editor_cancel">Abbrechen</string>
"""

# ── French ─────────────────────────────────────────────────────────────────
BLOCK_FR = """
    <!-- ── BATCH 5: SPARKS FEED ── -->
    <string name="sparks_feed_no_sparks">Aucun spark disponible</string>
    <string name="sparks_feed_back">Retour</string>
    <string name="sparks_feed_search">Rechercher</string>
    <string name="sparks_feed_create">Cr\u00e9er un Spark</string>
    <string name="sparks_feed_my_profile">Mon profil</string>
    <string name="sparks_feed_search_placeholder">Rechercher sparks, cr\u00e9ateurs, #tags\u2026</string>
    <string name="sparks_feed_search_close">Fermer</string>
    <string name="sparks_feed_popular_tags">Tags populaires</string>
    <string name="sparks_feed_section_sparks">Sparks</string>
    <string name="sparks_feed_section_posts">Publications</string>
    <string name="sparks_feed_section_people">Personnes</string>
    <string name="sparks_feed_no_results">Aucun r\u00e9sultat pour \u00ab\u00a0%1$s\u00a0\u00bb</string>
    <string name="sparks_feed_show_fullscreen">Afficher en plein \u00e9cran</string>
    <string name="sparks_feed_exit_fullscreen">Quitter le plein \u00e9cran</string>
    <string name="sparks_feed_play">Lire</string>
    <string name="sparks_feed_creator">Cr\u00e9ateur</string>
    <string name="sparks_feed_subscribed">Abonnement Spark ajout\u00e9\u00a0!</string>
    <string name="sparks_feed_action_like">Like</string>
    <string name="sparks_feed_action_comment">Commentaire</string>
    <string name="sparks_feed_action_gift">Cadeau</string>
    <string name="sparks_feed_action_share">Partager</string>
    <string name="sparks_feed_comment_placeholder">Commenter\u2026</string>
    <string name="sparks_feed_send">Envoyer</string>
    <string name="sparks_feed_comments_count">%1$d commentaires</string>
    <string name="sparks_feed_no_comments">Pas encore de commentaires. Sois le premier\u00a0!</string>
    <string name="sparks_feed_reply_to">R\u00e9pondre \u00e0 @%1$s</string>
    <string name="sparks_feed_spark_link_label">Spark</string>
    <string name="sparks_feed_spark_link_tap">Appuyer pour ouvrir</string>
    <string name="sparks_feed_unknown_user">Inconnu</string>
    <string name="sparks_feed_gift_title">Offrir des Styx</string>
    <string name="sparks_feed_gift_support">Soutiens %1$s avec des Styx\u00a0!</string>
    <string name="sparks_feed_gift_balance">Ton solde\u00a0: %1$d Styx</string>
    <string name="sparks_feed_gift_sent">%1$d Styx offerts\u00a0!</string>
    <string name="sparks_feed_gift_not_enough">Pas assez de Styx\u00a0!</string>
    <string name="sparks_feed_gift_close">Fermer</string>
    <string name="sparks_feed_share_title">Partager le Spark</string>
    <string name="sparks_feed_share_external">Partager en externe</string>
    <string name="sparks_feed_share_external_subtitle">Partager le lien via d\'autres applications</string>
    <string name="sparks_feed_share_copy_link">Copier le lien</string>
    <string name="sparks_feed_share_copy_link_subtitle">Lien externe (web/navigateur)</string>
    <string name="sparks_feed_share_link_copied">Lien copi\u00e9\u00a0!</string>
    <string name="sparks_feed_share_send_to">Envoyer \u00e0 un contact</string>
    <string name="sparks_feed_no_contacts">Aucun contact disponible</string>
    <string name="sparks_feed_sent_to">Envoy\u00e9 \u00e0 %1$s</string>
    <!-- ── BATCH 5: SPARK STATS ── -->
    <string name="spark_stats_title">Statistiques Spark</string>
    <string name="spark_stats_back">Retour</string>
    <string name="spark_stats_overview">Vue d\'ensemble</string>
    <string name="spark_stats_views">Vues</string>
    <string name="spark_stats_likes">Likes</string>
    <string name="spark_stats_subscribers">Abonn\u00e9s</string>
    <string name="spark_stats_avg_watchtime">Temps de visionnage moy.\u00a0: %1$ss</string>
    <string name="spark_stats_per_spark">Par Spark</string>
    <string name="spark_stats_no_sparks">Pas encore de Sparks.</string>
    <string name="spark_stats_loops">Boucles</string>
    <string name="spark_stats_skips">Sauts</string>
    <string name="spark_stats_avg_duration">\u00d8 Temps de visionnage\u00a0: %1$ss</string>
    <!-- ── BATCH 5: SPARK EDITOR ── -->
    <string name="spark_editor_cancel">Annuler</string>
    <string name="spark_editor_back_to_editor">Retour \u00e0 l\'éditeur</string>
    <string name="spark_editor_display_duration">Dur\u00e9e d\'affichage</string>
    <string name="spark_editor_music_start">Point de d\u00e9part de la musique</string>
    <string name="spark_editor_title_label">Titre</string>
    <string name="spark_editor_title_placeholder">Donne un titre \u00e0 ton Spark\u2026</string>
    <string name="spark_editor_description_label">Description \u00b7 #Tags \u00b7 @Mentions</string>
    <string name="spark_editor_description_placeholder">D\u00e9cris ton Spark\u2026 #Hashtags et @username possibles</string>
    <string name="spark_editor_create_button">Cr\u00e9er le Spark</string>
    <string name="spark_editor_create_hint">Le Spark sera visible dans ton profil cr\u00e9ateur et dans le fil Spark apr\u00e8s cr\u00e9ation.</string>
    <string name="spark_editor_clip_suffix">extrait</string>
    <string name="spark_editor_uploading">Spark</string>
    <string name="spark_editor_do_not_close">Veuillez ne pas fermer</string>
    <string name="spark_editor_music_choose">Choisir de la musique</string>
    <string name="spark_editor_audius_library">Biblioth\u00e8que Audius</string>
    <string name="spark_editor_music_search_placeholder">Rechercher de la musique\u2026 (ex. \u00ab\u00a0electronic\u00a0\u00bb, \u00ab\u00a0hip hop\u00a0\u00bb)</string>
    <string name="spark_editor_track_selected">S\u00e9lectionn\u00e9\u00a0: %1$s</string>
    <string name="spark_editor_ok">OK</string>
    <string name="spark_editor_no_tracks">Aucun titre pour \u00ab\u00a0%1$s\u00a0\u00bb.</string>
    <string name="spark_editor_add_details">Ajouter des d\u00e9tails</string>
    <!-- ── BATCH 5: CREATOR DASHBOARD ── -->
    <string name="creator_dash_title">Tableau de bord cr\u00e9ateur</string>
    <string name="creator_dash_more">Plus</string>
    <string name="creator_dash_spark_stats">Statistiques Spark</string>
    <string name="creator_dash_livestream">Livestream</string>
    <string name="creator_dash_new_content">Nouveau contenu</string>
    <string name="creator_dash_live_badge">LIVE</string>
    <string name="creator_dash_diamonds">Diamants</string>
    <string name="creator_dash_change_price">Modifier le prix d\'abonnement</string>
    <string name="creator_dash_set_username">D\u00e9finir un nom d\'utilisateur</string>
    <string name="creator_dash_edit_username">Modifier le nom d\'utilisateur</string>
    <string name="creator_dash_tab_content">Contenu</string>
    <string name="creator_dash_tab_sparks">Sparks</string>
    <string name="creator_dash_no_content">Pas encore de contenu.\\nT\u00e9l\u00e9charge ta premi\u00e8re publication\u00a0!</string>
    <string name="creator_dash_no_sparks">Pas encore de Sparks.\\nT\u00e9l\u00e9charge ta premi\u00e8re vid\u00e9o courte\u00a0!</string>
    <string name="creator_dash_create_post">Cr\u00e9er une publication</string>
    <string name="creator_dash_create_post_subtitle">Article avec texte, images et vid\u00e9os</string>
    <string name="creator_dash_create_spark">Cr\u00e9er un Spark</string>
    <string name="creator_dash_create_spark_subtitle">Vid\u00e9o courte (toujours gratuite pour les abonn\u00e9s)</string>
    <string name="creator_dash_create_livestream">Livestream</string>
    <string name="creator_dash_create_livestream_subtitle">Passe en direct \u2013 les spectateurs voient ton stream</string>
    <string name="creator_dash_price_dialog_title">Modifier le prix d\'abonnement</string>
    <string name="creator_dash_price_free">0 Styx = gratuit pour tous</string>
    <string name="creator_dash_price_label">Prix en Styx</string>
    <string name="creator_dash_save">Enregistrer</string>
    <string name="creator_dash_cancel">Annuler</string>
    <string name="creator_dash_username_title">Nom d\'utilisateur</string>
    <string name="creator_dash_username_label">@Nom d\'utilisateur (max. 50 caract\u00e8res)</string>
    <string name="creator_dash_delete_spark_title">Supprimer le Spark\u00a0?</string>
    <string name="creator_dash_delete_post_title">Supprimer la publication\u00a0?</string>
    <string name="creator_dash_delete_confirm">\u00ab\u00a0%1$s\u00a0\u00bb supprim\u00e9 d\u00e9finitivement\u00a0?</string>
    <string name="creator_dash_delete_button">Supprimer</string>
    <string name="creator_dash_banner_title">T\u00e9l\u00e9charger une banni\u00e8re</string>
    <string name="creator_dash_banner_hint">Recommand\u00e9\u00a0: 1500\u00d7500 px, JPG ou PNG, max. 5 Mo.\\nFormat paysage large, sans contenu important sur les bords.</string>
    <string name="creator_dash_avatar_title">T\u00e9l\u00e9charger une photo de profil</string>
    <string name="creator_dash_avatar_hint">Recommand\u00e9\u00a0: 400\u00d7400 px, JPG ou PNG, max. 2 Mo.\\nImage carr\u00e9e, visage bien visible.</string>
    <string name="creator_dash_choose_image">Choisir une image</string>
    <string name="creator_dash_banner_cd">Banni\u00e8re cr\u00e9ateur</string>
    <string name="creator_dash_edit_banner">Modifier la banni\u00e8re</string>
    <string name="creator_dash_profile_image_cd">Photo de profil cr\u00e9ateur</string>
    <string name="creator_dash_edit_avatar">Modifier la photo de profil</string>
    <string name="creator_dash_content_preview">Aper\u00e7u du contenu</string>
    <string name="creator_dash_edit">Modifier</string>
    <string name="creator_dash_delete">Supprimer</string>
    <string name="creator_dash_play">Lire</string>
    <string name="creator_dash_spark_thumbnail">Miniature Spark</string>
    <!-- ── BATCH 5: IMAGE EDITOR ── -->
    <string name="image_editor_close">Fermer</string>
    <string name="image_editor_title">Modifier l\'image</string>
    <string name="image_editor_undo">Annuler</string>
    <string name="image_editor_add_text">Texte</string>
    <string name="image_editor_brush_size">Taille du pinceau</string>
    <string name="image_editor_send">Envoyer</string>
    <string name="image_editor_size_label">Taille</string>
    <string name="image_editor_text_dialog_title">Ajouter du texte</string>
    <string name="image_editor_text_input_label">Saisir du texte</string>
    <string name="image_editor_text_color_label">Couleur\u00a0:</string>
    <string name="image_editor_add_button">Ajouter</string>
    <string name="image_editor_cancel">Annuler</string>
"""

# ── Spanish ────────────────────────────────────────────────────────────────
BLOCK_ES = """
    <!-- ── BATCH 5: SPARKS FEED ── -->
    <string name="sparks_feed_no_sparks">No hay sparks disponibles</string>
    <string name="sparks_feed_back">Atr\u00e1s</string>
    <string name="sparks_feed_search">Buscar</string>
    <string name="sparks_feed_create">Crear Spark</string>
    <string name="sparks_feed_my_profile">Mi perfil</string>
    <string name="sparks_feed_search_placeholder">Buscar sparks, creadores, #etiquetas\u2026</string>
    <string name="sparks_feed_search_close">Cerrar</string>
    <string name="sparks_feed_popular_tags">Etiquetas populares</string>
    <string name="sparks_feed_section_sparks">Sparks</string>
    <string name="sparks_feed_section_posts">Publicaciones</string>
    <string name="sparks_feed_section_people">Personas</string>
    <string name="sparks_feed_no_results">Sin resultados para \u00ab%1$s\u00bb</string>
    <string name="sparks_feed_show_fullscreen">Ver en pantalla completa</string>
    <string name="sparks_feed_exit_fullscreen">Salir de pantalla completa</string>
    <string name="sparks_feed_play">Reproducir</string>
    <string name="sparks_feed_creator">Creador</string>
    <string name="sparks_feed_subscribed">\u00a1Suscripci\u00f3n al Spark a\u00f1adida!</string>
    <string name="sparks_feed_action_like">Me gusta</string>
    <string name="sparks_feed_action_comment">Comentario</string>
    <string name="sparks_feed_action_gift">Regalo</string>
    <string name="sparks_feed_action_share">Compartir</string>
    <string name="sparks_feed_comment_placeholder">Comentar\u2026</string>
    <string name="sparks_feed_send">Enviar</string>
    <string name="sparks_feed_comments_count">%1$d comentarios</string>
    <string name="sparks_feed_no_comments">\u00a1A\u00fan no hay comentarios. \u00a1S\u00e9 el primero!</string>
    <string name="sparks_feed_reply_to">Responder a @%1$s</string>
    <string name="sparks_feed_spark_link_label">Spark</string>
    <string name="sparks_feed_spark_link_tap">Pulsar para abrir</string>
    <string name="sparks_feed_unknown_user">Desconocido</string>
    <string name="sparks_feed_gift_title">Regalar Styx</string>
    <string name="sparks_feed_gift_support">\u00a1Apoya a %1$s con Styx!</string>
    <string name="sparks_feed_gift_balance">Tu saldo: %1$d Styx</string>
    <string name="sparks_feed_gift_sent">\u00a1%1$d Styx regalados!</string>
    <string name="sparks_feed_gift_not_enough">\u00a1No tienes suficientes Styx!</string>
    <string name="sparks_feed_gift_close">Cerrar</string>
    <string name="sparks_feed_share_title">Compartir Spark</string>
    <string name="sparks_feed_share_external">Compartir externamente</string>
    <string name="sparks_feed_share_external_subtitle">Compartir enlace a trav\u00e9s de otras apps</string>
    <string name="sparks_feed_share_copy_link">Copiar enlace</string>
    <string name="sparks_feed_share_copy_link_subtitle">Enlace externo (web/navegador)</string>
    <string name="sparks_feed_share_link_copied">\u00a1Enlace copiado!</string>
    <string name="sparks_feed_share_send_to">Enviar a contacto</string>
    <string name="sparks_feed_no_contacts">No hay contactos disponibles</string>
    <string name="sparks_feed_sent_to">Enviado a %1$s</string>
    <!-- ── BATCH 5: SPARK STATS ── -->
    <string name="spark_stats_title">Estad\u00edsticas de Spark</string>
    <string name="spark_stats_back">Atr\u00e1s</string>
    <string name="spark_stats_overview">Resumen general</string>
    <string name="spark_stats_views">Vistas</string>
    <string name="spark_stats_likes">Me gusta</string>
    <string name="spark_stats_subscribers">Suscriptores</string>
    <string name="spark_stats_avg_watchtime">Tiempo de visualizaci\u00f3n prom.: %1$ss</string>
    <string name="spark_stats_per_spark">Por Spark</string>
    <string name="spark_stats_no_sparks">A\u00fan no hay Sparks.</string>
    <string name="spark_stats_loops">Repeticiones</string>
    <string name="spark_stats_skips">Saltos</string>
    <string name="spark_stats_avg_duration">\u00d8 Visualizaci\u00f3n: %1$ss</string>
    <!-- ── BATCH 5: SPARK EDITOR ── -->
    <string name="spark_editor_cancel">Cancelar</string>
    <string name="spark_editor_back_to_editor">Volver al editor</string>
    <string name="spark_editor_display_duration">Duraci\u00f3n de visualizaci\u00f3n</string>
    <string name="spark_editor_music_start">Punto de inicio de m\u00fasica</string>
    <string name="spark_editor_title_label">T\u00edtulo</string>
    <string name="spark_editor_title_placeholder">Dale un t\u00edtulo a tu Spark\u2026</string>
    <string name="spark_editor_description_label">Descripci\u00f3n \u00b7 #Etiquetas \u00b7 @Menciones</string>
    <string name="spark_editor_description_placeholder">Describe tu Spark\u2026 #Hashtags y @usuario son posibles</string>
    <string name="spark_editor_create_button">Crear Spark</string>
    <string name="spark_editor_create_hint">El Spark ser\u00e1 visible en tu perfil de creador y en el feed de Sparks tras crearlo.</string>
    <string name="spark_editor_clip_suffix">fragmento</string>
    <string name="spark_editor_uploading">Spark</string>
    <string name="spark_editor_do_not_close">Por favor, no cierres</string>
    <string name="spark_editor_music_choose">Elegir m\u00fasica</string>
    <string name="spark_editor_audius_library">Biblioteca Audius</string>
    <string name="spark_editor_music_search_placeholder">Buscar m\u00fasica\u2026 (ej. \u00abelectr\u00f3nica\u00bb, \u00abhip hop\u00bb, \u00abchill\u00bb)</string>
    <string name="spark_editor_track_selected">Seleccionado: %1$s</string>
    <string name="spark_editor_ok">OK</string>
    <string name="spark_editor_no_tracks">No hay pistas para \u00ab%1$s\u00bb.</string>
    <string name="spark_editor_add_details">A\u00f1adir detalles</string>
    <!-- ── BATCH 5: CREATOR DASHBOARD ── -->
    <string name="creator_dash_title">Panel del creador</string>
    <string name="creator_dash_more">M\u00e1s</string>
    <string name="creator_dash_spark_stats">Estad\u00edsticas de Spark</string>
    <string name="creator_dash_livestream">Livestream</string>
    <string name="creator_dash_new_content">Nuevo contenido</string>
    <string name="creator_dash_live_badge">DIRECTO</string>
    <string name="creator_dash_diamonds">Diamantes</string>
    <string name="creator_dash_change_price">Cambiar precio de suscripci\u00f3n</string>
    <string name="creator_dash_set_username">Establecer nombre de usuario</string>
    <string name="creator_dash_edit_username">Editar nombre de usuario</string>
    <string name="creator_dash_tab_content">Contenido</string>
    <string name="creator_dash_tab_sparks">Sparks</string>
    <string name="creator_dash_no_content">A\u00fan sin contenido.\\n\u00a1Sube tu primera publicaci\u00f3n!</string>
    <string name="creator_dash_no_sparks">A\u00fan sin Sparks.\\n\u00a1Sube tu primer v\u00eddeo corto!</string>
    <string name="creator_dash_create_post">Crear publicaci\u00f3n</string>
    <string name="creator_dash_create_post_subtitle">Art\u00edculo con texto, im\u00e1genes y v\u00eddeos</string>
    <string name="creator_dash_create_spark">Crear Spark</string>
    <string name="creator_dash_create_spark_subtitle">V\u00eddeo corto (siempre gratuito para suscriptores)</string>
    <string name="creator_dash_create_livestream">Livestream</string>
    <string name="creator_dash_create_livestream_subtitle">Ponte en directo \u2013 los espectadores ver\u00e1n tu stream</string>
    <string name="creator_dash_price_dialog_title">Cambiar precio de suscripci\u00f3n</string>
    <string name="creator_dash_price_free">0 Styx = gratuito para todos</string>
    <string name="creator_dash_price_label">Precio en Styx</string>
    <string name="creator_dash_save">Guardar</string>
    <string name="creator_dash_cancel">Cancelar</string>
    <string name="creator_dash_username_title">Nombre de usuario</string>
    <string name="creator_dash_username_label">@Nombre de usuario (m\u00e1x. 50 caracteres)</string>
    <string name="creator_dash_delete_spark_title">\u00bfEliminar Spark?</string>
    <string name="creator_dash_delete_post_title">\u00bfEliminar publicaci\u00f3n?</string>
    <string name="creator_dash_delete_confirm">\u00bfEliminar \u00ab%1$s\u00bb permanentemente?</string>
    <string name="creator_dash_delete_button">Eliminar</string>
    <string name="creator_dash_banner_title">Subir banner</string>
    <string name="creator_dash_banner_hint">Recomendado: 1500\u00d7500 px, JPG o PNG, m\u00e1x. 5 MB.\\nFormato horizontal, sin contenido importante en los bordes.</string>
    <string name="creator_dash_avatar_title">Subir foto de perfil</string>
    <string name="creator_dash_avatar_hint">Recomendado: 400\u00d7400 px, JPG o PNG, m\u00e1x. 2 MB.\\nImagen cuadrada, cara bien visible.</string>
    <string name="creator_dash_choose_image">Elegir imagen</string>
    <string name="creator_dash_banner_cd">Banner del creador</string>
    <string name="creator_dash_edit_banner">Editar banner</string>
    <string name="creator_dash_profile_image_cd">Foto de perfil del creador</string>
    <string name="creator_dash_edit_avatar">Editar foto de perfil</string>
    <string name="creator_dash_content_preview">Vista previa del contenido</string>
    <string name="creator_dash_edit">Editar</string>
    <string name="creator_dash_delete">Eliminar</string>
    <string name="creator_dash_play">Reproducir</string>
    <string name="creator_dash_spark_thumbnail">Miniatura del Spark</string>
    <!-- ── BATCH 5: IMAGE EDITOR ── -->
    <string name="image_editor_close">Cerrar</string>
    <string name="image_editor_title">Editar imagen</string>
    <string name="image_editor_undo">Deshacer</string>
    <string name="image_editor_add_text">Texto</string>
    <string name="image_editor_brush_size">Tama\u00f1o del pincel</string>
    <string name="image_editor_send">Enviar</string>
    <string name="image_editor_size_label">Tama\u00f1o</string>
    <string name="image_editor_text_dialog_title">A\u00f1adir texto</string>
    <string name="image_editor_text_input_label">Introducir texto</string>
    <string name="image_editor_text_color_label">Color:</string>
    <string name="image_editor_add_button">A\u00f1adir</string>
    <string name="image_editor_cancel">Cancelar</string>
"""

# ── Dutch ──────────────────────────────────────────────────────────────────
BLOCK_NL = """
    <!-- ── BATCH 5: SPARKS FEED ── -->
    <string name="sparks_feed_no_sparks">Geen sparks beschikbaar</string>
    <string name="sparks_feed_back">Terug</string>
    <string name="sparks_feed_search">Zoeken</string>
    <string name="sparks_feed_create">Spark maken</string>
    <string name="sparks_feed_my_profile">Mijn profiel</string>
    <string name="sparks_feed_search_placeholder">Zoek sparks, creators, #tags\u2026</string>
    <string name="sparks_feed_search_close">Sluiten</string>
    <string name="sparks_feed_popular_tags">Populaire tags</string>
    <string name="sparks_feed_section_sparks">Sparks</string>
    <string name="sparks_feed_section_posts">Berichten</string>
    <string name="sparks_feed_section_people">Personen</string>
    <string name="sparks_feed_no_results">Geen resultaten voor \u201e%1$s\u201c</string>
    <string name="sparks_feed_show_fullscreen">Volledig scherm weergeven</string>
    <string name="sparks_feed_exit_fullscreen">Volledig scherm sluiten</string>
    <string name="sparks_feed_play">Afspelen</string>
    <string name="sparks_feed_creator">Creator</string>
    <string name="sparks_feed_subscribed">Spark-abonnement toegevoegd!</string>
    <string name="sparks_feed_action_like">Like</string>
    <string name="sparks_feed_action_comment">Reactie</string>
    <string name="sparks_feed_action_gift">Cadeau</string>
    <string name="sparks_feed_action_share">Delen</string>
    <string name="sparks_feed_comment_placeholder">Reageren\u2026</string>
    <string name="sparks_feed_send">Verzenden</string>
    <string name="sparks_feed_comments_count">%1$d reacties</string>
    <string name="sparks_feed_no_comments">Nog geen reacties. Wees de eerste!</string>
    <string name="sparks_feed_reply_to">Antwoord aan @%1$s</string>
    <string name="sparks_feed_spark_link_label">Spark</string>
    <string name="sparks_feed_spark_link_tap">Tikken om te openen</string>
    <string name="sparks_feed_unknown_user">Onbekend</string>
    <string name="sparks_feed_gift_title">Styx schenken</string>
    <string name="sparks_feed_gift_support">Steun %1$s met Styx!</string>
    <string name="sparks_feed_gift_balance">Jouw saldo: %1$d Styx</string>
    <string name="sparks_feed_gift_sent">%1$d Styx geschonken!</string>
    <string name="sparks_feed_gift_not_enough">Niet genoeg Styx!</string>
    <string name="sparks_feed_gift_close">Sluiten</string>
    <string name="sparks_feed_share_title">Spark delen</string>
    <string name="sparks_feed_share_external">Extern delen</string>
    <string name="sparks_feed_share_external_subtitle">Link via andere apps delen</string>
    <string name="sparks_feed_share_copy_link">Link kopi\u00ebren</string>
    <string name="sparks_feed_share_copy_link_subtitle">Externe link (web/browser)</string>
    <string name="sparks_feed_share_link_copied">Link gekopieerd!</string>
    <string name="sparks_feed_share_send_to">Naar contact sturen</string>
    <string name="sparks_feed_no_contacts">Geen contacten beschikbaar</string>
    <string name="sparks_feed_sent_to">Verzonden naar %1$s</string>
    <!-- ── BATCH 5: SPARK STATS ── -->
    <string name="spark_stats_title">Spark-statistieken</string>
    <string name="spark_stats_back">Terug</string>
    <string name="spark_stats_overview">Totaaloverzicht</string>
    <string name="spark_stats_views">Weergaven</string>
    <string name="spark_stats_likes">Likes</string>
    <string name="spark_stats_subscribers">Abonnees</string>
    <string name="spark_stats_avg_watchtime">Gem. kijktijd: %1$ss</string>
    <string name="spark_stats_per_spark">Per Spark</string>
    <string name="spark_stats_no_sparks">Nog geen Sparks.</string>
    <string name="spark_stats_loops">Herhalingen</string>
    <string name="spark_stats_skips">Overslagen</string>
    <string name="spark_stats_avg_duration">\u00d8 Kijktijd: %1$ss</string>
    <!-- ── BATCH 5: SPARK EDITOR ── -->
    <string name="spark_editor_cancel">Annuleren</string>
    <string name="spark_editor_back_to_editor">Terug naar editor</string>
    <string name="spark_editor_display_duration">Weergaveduur</string>
    <string name="spark_editor_music_start">Startpunt muziek</string>
    <string name="spark_editor_title_label">Titel</string>
    <string name="spark_editor_title_placeholder">Geef je Spark een titel\u2026</string>
    <string name="spark_editor_description_label">Beschrijving \u00b7 #Tags \u00b7 @Vermeldingen</string>
    <string name="spark_editor_description_placeholder">Beschrijf je Spark\u2026 #Hashtags en @gebruikersnaam zijn mogelijk</string>
    <string name="spark_editor_create_button">Spark maken</string>
    <string name="spark_editor_create_hint">De Spark is na aanmaken zichtbaar in je creator-profiel en in de Spark-feed.</string>
    <string name="spark_editor_clip_suffix">fragment</string>
    <string name="spark_editor_uploading">Spark</string>
    <string name="spark_editor_do_not_close">Sluit dit venster niet</string>
    <string name="spark_editor_music_choose">Muziek kiezen</string>
    <string name="spark_editor_audius_library">Audius-bibliotheek</string>
    <string name="spark_editor_music_search_placeholder">Muziek zoeken\u2026 (bijv. \u201eelectronic\u201c, \u201ehip hop\u201c)</string>
    <string name="spark_editor_track_selected">Geselecteerd: %1$s</string>
    <string name="spark_editor_ok">OK</string>
    <string name="spark_editor_no_tracks">Geen nummers gevonden voor \u201e%1$s\u201c.</string>
    <string name="spark_editor_add_details">Details toevoegen</string>
    <!-- ── BATCH 5: CREATOR DASHBOARD ── -->
    <string name="creator_dash_title">Creator-dashboard</string>
    <string name="creator_dash_more">Meer</string>
    <string name="creator_dash_spark_stats">Spark-statistieken</string>
    <string name="creator_dash_livestream">Livestream</string>
    <string name="creator_dash_new_content">Nieuwe inhoud</string>
    <string name="creator_dash_live_badge">LIVE</string>
    <string name="creator_dash_diamonds">Diamanten</string>
    <string name="creator_dash_change_price">Abonnementsprijs wijzigen</string>
    <string name="creator_dash_set_username">Gebruikersnaam instellen</string>
    <string name="creator_dash_edit_username">Gebruikersnaam bewerken</string>
    <string name="creator_dash_tab_content">Inhoud</string>
    <string name="creator_dash_tab_sparks">Sparks</string>
    <string name="creator_dash_no_content">Nog geen inhoud.\\nUpload je eerste bericht!</string>
    <string name="creator_dash_no_sparks">Nog geen Sparks.\\nUpload je eerste korte video!</string>
    <string name="creator_dash_create_post">Bericht aanmaken</string>
    <string name="creator_dash_create_post_subtitle">Artikel met tekst, afbeeldingen en video\'s</string>
    <string name="creator_dash_create_spark">Spark aanmaken</string>
    <string name="creator_dash_create_spark_subtitle">Korte video (altijd gratis voor abonnees)</string>
    <string name="creator_dash_create_livestream">Livestream</string>
    <string name="creator_dash_create_livestream_subtitle">Ga live \u2013 kijkers zien jouw stream</string>
    <string name="creator_dash_price_dialog_title">Abonnementsprijs wijzigen</string>
    <string name="creator_dash_price_free">0 Styx = gratis voor iedereen</string>
    <string name="creator_dash_price_label">Prijs in Styx</string>
    <string name="creator_dash_save">Opslaan</string>
    <string name="creator_dash_cancel">Annuleren</string>
    <string name="creator_dash_username_title">Gebruikersnaam</string>
    <string name="creator_dash_username_label">@Gebruikersnaam (max. 50 tekens)</string>
    <string name="creator_dash_delete_spark_title">Spark verwijderen?</string>
    <string name="creator_dash_delete_post_title">Bericht verwijderen?</string>
    <string name="creator_dash_delete_confirm">\u201e%1$s\u201c definitief verwijderen?</string>
    <string name="creator_dash_delete_button">Verwijderen</string>
    <string name="creator_dash_banner_title">Banner uploaden</string>
    <string name="creator_dash_banner_hint">Aanbevolen: 1500\u00d7500 px, JPG of PNG, max. 5 MB.\\nBreed landschapsformaat, geen belangrijke inhoud aan de randen.</string>
    <string name="creator_dash_avatar_title">Profielfoto uploaden</string>
    <string name="creator_dash_avatar_hint">Aanbevolen: 400\u00d7400 px, JPG of PNG, max. 2 MB.\\nVierkante afbeelding, gezicht goed zichtbaar.</string>
    <string name="creator_dash_choose_image">Afbeelding kiezen</string>
    <string name="creator_dash_banner_cd">Creator-banner</string>
    <string name="creator_dash_edit_banner">Banner bewerken</string>
    <string name="creator_dash_profile_image_cd">Creator-profielfoto</string>
    <string name="creator_dash_edit_avatar">Profielfoto bewerken</string>
    <string name="creator_dash_content_preview">Inhoudsvoorbeeld</string>
    <string name="creator_dash_edit">Bewerken</string>
    <string name="creator_dash_delete">Verwijderen</string>
    <string name="creator_dash_play">Afspelen</string>
    <string name="creator_dash_spark_thumbnail">Spark-miniatuur</string>
    <!-- ── BATCH 5: IMAGE EDITOR ── -->
    <string name="image_editor_close">Sluiten</string>
    <string name="image_editor_title">Afbeelding bewerken</string>
    <string name="image_editor_undo">Ongedaan maken</string>
    <string name="image_editor_add_text">Tekst</string>
    <string name="image_editor_brush_size">Penseelgrootte</string>
    <string name="image_editor_send">Verzenden</string>
    <string name="image_editor_size_label">Grootte</string>
    <string name="image_editor_text_dialog_title">Tekst toevoegen</string>
    <string name="image_editor_text_input_label">Tekst invoeren</string>
    <string name="image_editor_text_color_label">Kleur:</string>
    <string name="image_editor_add_button">Toevoegen</string>
    <string name="image_editor_cancel">Annuleren</string>
"""

# ── Italian ────────────────────────────────────────────────────────────────
BLOCK_IT = """
    <!-- ── BATCH 5: SPARKS FEED ── -->
    <string name="sparks_feed_no_sparks">Nessun spark disponibile</string>
    <string name="sparks_feed_back">Indietro</string>
    <string name="sparks_feed_search">Cerca</string>
    <string name="sparks_feed_create">Crea Spark</string>
    <string name="sparks_feed_my_profile">Il mio profilo</string>
    <string name="sparks_feed_search_placeholder">Cerca spark, creator, #tag\u2026</string>
    <string name="sparks_feed_search_close">Chiudi</string>
    <string name="sparks_feed_popular_tags">Tag popolari</string>
    <string name="sparks_feed_section_sparks">Sparks</string>
    <string name="sparks_feed_section_posts">Post</string>
    <string name="sparks_feed_section_people">Persone</string>
    <string name="sparks_feed_no_results">Nessun risultato per \u00ab%1$s\u00bb</string>
    <string name="sparks_feed_show_fullscreen">Mostra a schermo intero</string>
    <string name="sparks_feed_exit_fullscreen">Esci dallo schermo intero</string>
    <string name="sparks_feed_play">Riproduci</string>
    <string name="sparks_feed_creator">Creator</string>
    <string name="sparks_feed_subscribed">Abbonamento Spark aggiunto!</string>
    <string name="sparks_feed_action_like">Mi piace</string>
    <string name="sparks_feed_action_comment">Commento</string>
    <string name="sparks_feed_action_gift">Regalo</string>
    <string name="sparks_feed_action_share">Condividi</string>
    <string name="sparks_feed_comment_placeholder">Commenta\u2026</string>
    <string name="sparks_feed_send">Invia</string>
    <string name="sparks_feed_comments_count">%1$d commenti</string>
    <string name="sparks_feed_no_comments">Ancora nessun commento. Sii il primo!</string>
    <string name="sparks_feed_reply_to">Rispondi a @%1$s</string>
    <string name="sparks_feed_spark_link_label">Spark</string>
    <string name="sparks_feed_spark_link_tap">Tocca per aprire</string>
    <string name="sparks_feed_unknown_user">Sconosciuto</string>
    <string name="sparks_feed_gift_title">Regala Styx</string>
    <string name="sparks_feed_gift_support">Supporta %1$s con Styx!</string>
    <string name="sparks_feed_gift_balance">Il tuo saldo: %1$d Styx</string>
    <string name="sparks_feed_gift_sent">%1$d Styx regalati!</string>
    <string name="sparks_feed_gift_not_enough">Styx insufficienti!</string>
    <string name="sparks_feed_gift_close">Chiudi</string>
    <string name="sparks_feed_share_title">Condividi Spark</string>
    <string name="sparks_feed_share_external">Condividi esternamente</string>
    <string name="sparks_feed_share_external_subtitle">Condividi il link tramite altre app</string>
    <string name="sparks_feed_share_copy_link">Copia link</string>
    <string name="sparks_feed_share_copy_link_subtitle">Link esterno (web/browser)</string>
    <string name="sparks_feed_share_link_copied">Link copiato!</string>
    <string name="sparks_feed_share_send_to">Invia a contatto</string>
    <string name="sparks_feed_no_contacts">Nessun contatto disponibile</string>
    <string name="sparks_feed_sent_to">Inviato a %1$s</string>
    <!-- ── BATCH 5: SPARK STATS ── -->
    <string name="spark_stats_title">Statistiche Spark</string>
    <string name="spark_stats_back">Indietro</string>
    <string name="spark_stats_overview">Panoramica generale</string>
    <string name="spark_stats_views">Visualizzazioni</string>
    <string name="spark_stats_likes">Mi piace</string>
    <string name="spark_stats_subscribers">Abbonati</string>
    <string name="spark_stats_avg_watchtime">Tempo di visualiz. medio: %1$ss</string>
    <string name="spark_stats_per_spark">Per Spark</string>
    <string name="spark_stats_no_sparks">Ancora nessun Spark.</string>
    <string name="spark_stats_loops">Loop</string>
    <string name="spark_stats_skips">Skip</string>
    <string name="spark_stats_avg_duration">\u00d8 Visualizzazione: %1$ss</string>
    <!-- ── BATCH 5: SPARK EDITOR ── -->
    <string name="spark_editor_cancel">Annulla</string>
    <string name="spark_editor_back_to_editor">Torna all\'editor</string>
    <string name="spark_editor_display_duration">Durata di visualizzazione</string>
    <string name="spark_editor_music_start">Punto di inizio musica</string>
    <string name="spark_editor_title_label">Titolo</string>
    <string name="spark_editor_title_placeholder">Dai un titolo al tuo Spark\u2026</string>
    <string name="spark_editor_description_label">Descrizione \u00b7 #Tag \u00b7 @Menzioni</string>
    <string name="spark_editor_description_placeholder">Descrivi il tuo Spark\u2026 #Hashtag e @utente sono possibili</string>
    <string name="spark_editor_create_button">Crea Spark</string>
    <string name="spark_editor_create_hint">Lo Spark sar\u00e0 visibile nel tuo profilo creator e nel feed Spark dopo la creazione.</string>
    <string name="spark_editor_clip_suffix">clip</string>
    <string name="spark_editor_uploading">Spark</string>
    <string name="spark_editor_do_not_close">Non chiudere</string>
    <string name="spark_editor_music_choose">Scegli musica</string>
    <string name="spark_editor_audius_library">Libreria Audius</string>
    <string name="spark_editor_music_search_placeholder">Cerca musica\u2026 (es. \u00abelectronic\u00bb, \u00abhip hop\u00bb, \u00abchill\u00bb)</string>
    <string name="spark_editor_track_selected">Selezionato: %1$s</string>
    <string name="spark_editor_ok">OK</string>
    <string name="spark_editor_no_tracks">Nessuna traccia per \u00ab%1$s\u00bb.</string>
    <string name="spark_editor_add_details">Aggiungi dettagli</string>
    <!-- ── BATCH 5: CREATOR DASHBOARD ── -->
    <string name="creator_dash_title">Dashboard creator</string>
    <string name="creator_dash_more">Altro</string>
    <string name="creator_dash_spark_stats">Statistiche Spark</string>
    <string name="creator_dash_livestream">Livestream</string>
    <string name="creator_dash_new_content">Nuovo contenuto</string>
    <string name="creator_dash_live_badge">LIVE</string>
    <string name="creator_dash_diamonds">Diamanti</string>
    <string name="creator_dash_change_price">Modifica prezzo abbonamento</string>
    <string name="creator_dash_set_username">Imposta nome utente</string>
    <string name="creator_dash_edit_username">Modifica nome utente</string>
    <string name="creator_dash_tab_content">Contenuto</string>
    <string name="creator_dash_tab_sparks">Sparks</string>
    <string name="creator_dash_no_content">Ancora nessun contenuto.\\nCarica il tuo primo post!</string>
    <string name="creator_dash_no_sparks">Ancora nessun Spark.\\nCarica il tuo primo video breve!</string>
    <string name="creator_dash_create_post">Crea post</string>
    <string name="creator_dash_create_post_subtitle">Articolo con testo, immagini e video</string>
    <string name="creator_dash_create_spark">Crea Spark</string>
    <string name="creator_dash_create_spark_subtitle">Video breve (sempre gratuito per gli abbonati)</string>
    <string name="creator_dash_create_livestream">Livestream</string>
    <string name="creator_dash_create_livestream_subtitle">Vai in diretta \u2013 gli spettatori vedono il tuo stream</string>
    <string name="creator_dash_price_dialog_title">Modifica prezzo abbonamento</string>
    <string name="creator_dash_price_free">0 Styx = gratuito per tutti</string>
    <string name="creator_dash_price_label">Prezzo in Styx</string>
    <string name="creator_dash_save">Salva</string>
    <string name="creator_dash_cancel">Annulla</string>
    <string name="creator_dash_username_title">Nome utente</string>
    <string name="creator_dash_username_label">@Nome utente (max. 50 caratteri)</string>
    <string name="creator_dash_delete_spark_title">Elimina Spark?</string>
    <string name="creator_dash_delete_post_title">Elimina post?</string>
    <string name="creator_dash_delete_confirm">Eliminare \u00ab%1$s\u00bb definitivamente?</string>
    <string name="creator_dash_delete_button">Elimina</string>
    <string name="creator_dash_banner_title">Carica banner</string>
    <string name="creator_dash_banner_hint">Consigliato: 1500\u00d7500 px, JPG o PNG, max. 5 MB.\\nFormato orizzontale ampio, senza contenuti importanti ai bordi.</string>
    <string name="creator_dash_avatar_title">Carica foto profilo</string>
    <string name="creator_dash_avatar_hint">Consigliato: 400\u00d7400 px, JPG o PNG, max. 2 MB.\\nImmagine quadrata, viso ben visibile.</string>
    <string name="creator_dash_choose_image">Scegli immagine</string>
    <string name="creator_dash_banner_cd">Banner creator</string>
    <string name="creator_dash_edit_banner">Modifica banner</string>
    <string name="creator_dash_profile_image_cd">Foto profilo creator</string>
    <string name="creator_dash_edit_avatar">Modifica foto profilo</string>
    <string name="creator_dash_content_preview">Anteprima contenuto</string>
    <string name="creator_dash_edit">Modifica</string>
    <string name="creator_dash_delete">Elimina</string>
    <string name="creator_dash_play">Riproduci</string>
    <string name="creator_dash_spark_thumbnail">Miniatura Spark</string>
    <!-- ── BATCH 5: IMAGE EDITOR ── -->
    <string name="image_editor_close">Chiudi</string>
    <string name="image_editor_title">Modifica immagine</string>
    <string name="image_editor_undo">Annulla</string>
    <string name="image_editor_add_text">Testo</string>
    <string name="image_editor_brush_size">Dimensione pennello</string>
    <string name="image_editor_send">Invia</string>
    <string name="image_editor_size_label">Dimensione</string>
    <string name="image_editor_text_dialog_title">Aggiungi testo</string>
    <string name="image_editor_text_input_label">Inserisci testo</string>
    <string name="image_editor_text_color_label">Colore:</string>
    <string name="image_editor_add_button">Aggiungi</string>
    <string name="image_editor_cancel">Annulla</string>
"""

files = {
    f"{BASE}/values/strings.xml": BLOCK_EN,
    f"{BASE}/values-en/strings.xml": BLOCK_EN,
    f"{BASE}/values-de/strings.xml": BLOCK_DE,
    f"{BASE}/values-fr/strings.xml": BLOCK_FR,
    f"{BASE}/values-es/strings.xml": BLOCK_ES,
    f"{BASE}/values-nl/strings.xml": BLOCK_NL,
    f"{BASE}/values-it/strings.xml": BLOCK_IT,
}

for path, block in files.items():
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    if 'sparks_feed_no_sparks' in content:
        print(f"SKIP (already done): {path}")
        continue
    content = content.replace('</resources>', block + '</resources>')
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Updated: {path}")

print("All done!")
